// <auto-generated />
using System;
using MIUPortal.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MIUPortal.API.Migrations
{
    [DbContext(typeof(MIUContext))]
    partial class MIUContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("MIUPortal.API.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("AdminCode")
                        .HasColumnType("longtext");

                    b.Property<string>("CampusCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("OtpCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("AdminId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Admins", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.Application", b =>
                {
                    b.Property<int>("ApplicationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ApplicationId"));

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("AdminNotes")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("AdminReviewDate")
                        .HasColumnType("datetime");

                    b.Property<string>("AdmissionLetterPath")
                        .HasColumnType("longtext");

                    b.Property<bool?>("AgreementAccepted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("AlevelCertificatePath")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ApplicationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("ApplicationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ApplicationStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("PENDING_OTP");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime");

                    b.Property<string>("CampusPreference")
                        .HasColumnType("longtext");

                    b.Property<string>("CertificateObtained")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("DigitalSignature")
                        .HasColumnType("longtext");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("longtext");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("EmergencyRelationship")
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Intake")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("NationalId")
                        .HasColumnType("longtext");

                    b.Property<string>("NationalIdPath")
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext");

                    b.Property<string>("OlevelCertificatePath")
                        .HasColumnType("longtext");

                    b.Property<string>("OtherCertificatesPath")
                        .HasColumnType("longtext");

                    b.Property<string>("OtpCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("OtpVerifiedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("PassportNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("PassportPhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<int?>("PaymentAmount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentProofPath")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("longtext")
                        .HasDefaultValue("PENDING");

                    b.Property<string>("PhysicalAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("PreviousSchool")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("ProgrammeCode")
                        .HasColumnType("longtext");

                    b.Property<string>("ProgrammeName")
                        .HasColumnType("longtext");

                    b.Property<string>("RegistrationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Religion")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ReviewDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ReviewedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("StudyMode")
                        .HasColumnType("longtext");

                    b.Property<string>("SubjectsPassed")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("WhatsappPhone")
                        .HasColumnType("longtext");

                    b.Property<int?>("YearOfCompletion")
                        .HasColumnType("int");

                    b.Property<int?>("YearOfEntry")
                        .HasColumnType("int");

                    b.HasKey("ApplicationId");

                    b.HasIndex("ApplicationNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RegistrationNumber")
                        .IsUnique();

                    b.ToTable("Applications", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.Campus", b =>
                {
                    b.Property<string>("CampusCode")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("CampusName")
                        .HasColumnType("longtext");

                    b.Property<string>("City")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("MainContactPerson")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.HasKey("CampusCode");

                    b.ToTable("Campuses", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("CourseName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int>("Credits")
                        .HasColumnType("int");

                    b.Property<bool?>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProgrammeCode")
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.HasKey("CourseId");

                    b.HasIndex("CourseCode")
                        .IsUnique();

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.CourseEnrollment", b =>
                {
                    b.Property<int>("EnrollmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("EnrollmentId"));

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Grade")
                        .HasColumnType("longtext");

                    b.Property<int?>("Mark")
                        .HasColumnType("int");

                    b.Property<string>("RegNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Semester")
                        .HasColumnType("int");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("EnrollmentId");

                    b.HasIndex("CourseId");

                    b.HasIndex("RegNumber", "CourseId", "Year", "SemesterId")
                        .IsUnique();

                    b.ToTable("CourseEnrollments", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.Document", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateDownloaded")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateGenerated")
                        .HasColumnType("datetime");

                    b.Property<decimal>("DocumentFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("DocumentType")
                        .HasColumnType("longtext");

                    b.Property<int>("DocumentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("datetime");

                    b.Property<bool>("FeePaid")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("FilePath")
                        .HasColumnType("longtext");

                    b.Property<int?>("GeneratedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("QrCodePath")
                        .HasColumnType("longtext");

                    b.Property<string>("QrVerificationCode")
                        .HasColumnType("longtext");

                    b.Property<string>("RegNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("DocumentId");

                    b.HasIndex("RegNumber");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.DocumentType", b =>
                {
                    b.Property<int>("DocumentTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("DocumentTypeId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<decimal>("DocumentFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("TypeName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("DocumentTypeId");

                    b.ToTable("DocumentTypes", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.FinancialTransaction", b =>
                {
                    b.Property<int>("LedgerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("LedgerId"));

                    b.Property<int>("Amount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Notes")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("PaymentReference")
                        .HasColumnType("longtext");

                    b.Property<string>("ReceiptPath")
                        .HasColumnType("longtext");

                    b.Property<string>("RegNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime");

                    b.Property<string>("TransactionType")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("LedgerId");

                    b.HasIndex("RegNumber");

                    b.ToTable("FinancialLedger", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateRead")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DateSent")
                        .HasColumnType("datetime");

                    b.Property<bool>("IsRead")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Message")
                        .HasColumnType("longtext");

                    b.Property<string>("RegNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("RelatedLink")
                        .HasColumnType("longtext");

                    b.Property<int?>("SentByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("NotificationId");

                    b.HasIndex("RegNumber");

                    b.ToTable("Notifications", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Network")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<int?>("ProcessedByAdminId")
                        .HasColumnType("int");

                    b.Property<bool>("ReceiptGenerated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ReceiptPath")
                        .HasColumnType("longtext");

                    b.Property<string>("RegNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<string>("TransactionReference")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("PaymentId");

                    b.HasIndex("RegNumber");

                    b.ToTable("Payments", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.PaymentGateway", b =>
                {
                    b.Property<int>("GatewayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("GatewayId"));

                    b.Property<string>("ApiKey")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("Currency")
                        .HasColumnType("longtext");

                    b.Property<string>("GatewayName")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("MaxAmount")
                        .HasColumnType("int");

                    b.Property<string>("MerchantId")
                        .HasColumnType("longtext");

                    b.Property<int?>("MinAmount")
                        .HasColumnType("int");

                    b.Property<string>("ProviderName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("GatewayId");

                    b.ToTable("PaymentGateways", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.Programme", b =>
                {
                    b.Property<string>("ProgrammeCode")
                        .HasColumnType("varchar(95)");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("DurationYears")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProgrammeLeader")
                        .HasColumnType("longtext");

                    b.Property<string>("ProgrammeName")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TuitionFeePerSemester")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("ProgrammeCode");

                    b.ToTable("Programmes", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.Result", b =>
                {
                    b.Property<int>("ResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ResultId"));

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime");

                    b.Property<int?>("ApprovedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("CourseCode")
                        .HasColumnType("longtext");

                    b.Property<string>("CourseName")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("CreditHours")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateUploaded")
                        .HasColumnType("datetime");

                    b.Property<string>("Grade")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("GradePoint")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal?>("Mark")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("RegNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("Semester")
                        .HasColumnType("int");

                    b.Property<int?>("SemesterId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<int?>("UploadedByAdminId")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("ResultId");

                    b.HasIndex("RegNumber");

                    b.ToTable("Results", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.SemesterRegistration", b =>
                {
                    b.Property<int>("RegistrationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("RegistrationId"));

                    b.Property<int>("AcademicYear")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("ExamPermitPath")
                        .HasColumnType("longtext");

                    b.Property<decimal>("FeePaid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("PercentagePaid")
                        .HasColumnType("int");

                    b.Property<string>("RegNumber")
                        .HasColumnType("varchar(50)");

                    b.Property<int>("RegisteredCourseCount")
                        .HasColumnType("int");

                    b.Property<string>("RegistrationCardPath")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Semester")
                        .HasColumnType("longtext");

                    b.Property<string>("Status")
                        .HasColumnType("longtext");

                    b.Property<decimal>("TotalFees")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.HasKey("RegistrationId");

                    b.HasIndex("RegNumber");

                    b.ToTable("SemesterRegistration", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.Student", b =>
                {
                    b.Property<string>("RegNumber")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("AdmissionLetterPath")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ApprovalDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("CGPA")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("CampusCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal?>("CurrentGPA")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int?>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime");

                    b.Property<string>("District")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool?>("EmailVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(false);

                    b.Property<string>("EmergencyContactName")
                        .HasColumnType("longtext");

                    b.Property<string>("EmergencyPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("EmergencyRelationship")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EnrolmentDate")
                        .HasColumnType("datetime");

                    b.Property<decimal?>("FeesBalance")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("Gender")
                        .HasColumnType("longtext");

                    b.Property<string>("Intake")
                        .HasColumnType("longtext");

                    b.Property<bool?>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("tinyint(1)")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("MaritalStatus")
                        .HasColumnType("longtext");

                    b.Property<string>("MiddleName")
                        .HasColumnType("longtext");

                    b.Property<string>("NationalId")
                        .HasColumnType("longtext");

                    b.Property<string>("Nationality")
                        .HasColumnType("longtext");

                    b.Property<string>("OtpCode")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("OtpExpiry")
                        .HasColumnType("datetime");

                    b.Property<string>("PassportPhotoPath")
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhysicalAddress")
                        .HasColumnType("longtext");

                    b.Property<string>("PrimaryPhone")
                        .HasColumnType("longtext");

                    b.Property<string>("ProgrammeCode")
                        .HasColumnType("longtext");

                    b.Property<string>("Religion")
                        .HasColumnType("longtext");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int");

                    b.Property<string>("StudyMode")
                        .HasColumnType("longtext");

                    b.Property<decimal?>("TotalPaid")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("WhatsappPhone")
                        .HasColumnType("longtext");

                    b.Property<int?>("YearOfEntry")
                        .HasColumnType("int");

                    b.HasKey("RegNumber");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.Timetable", b =>
                {
                    b.Property<int>("TimetableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("TimetableId"));

                    b.Property<string>("CampusCode")
                        .HasColumnType("longtext");

                    b.Property<string>("CourseCode")
                        .HasColumnType("longtext");

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<string>("CourseName")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime");

                    b.Property<string>("DayOfWeek")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime");

                    b.Property<TimeSpan?>("EndTime")
                        .HasColumnType("time");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Lecturer")
                        .HasColumnType("longtext");

                    b.Property<string>("ProgrammeCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ProgrammeName")
                        .HasColumnType("longtext");

                    b.Property<int>("Semester")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Venue")
                        .HasColumnType("longtext");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("TimetableId");

                    b.ToTable("Timetables", (string)null);
                });

            modelBuilder.Entity("MIUPortal.API.Models.CourseEnrollment", b =>
                {
                    b.HasOne("MIUPortal.API.Models.Course", "Course")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MIUPortal.API.Models.Student", "Student")
                        .WithMany("CourseEnrollments")
                        .HasForeignKey("RegNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MIUPortal.API.Models.Document", b =>
                {
                    b.HasOne("MIUPortal.API.Models.Student", "Student")
                        .WithMany("Documents")
                        .HasForeignKey("RegNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MIUPortal.API.Models.FinancialTransaction", b =>
                {
                    b.HasOne("MIUPortal.API.Models.Student", "Student")
                        .WithMany("FinancialTransactions")
                        .HasForeignKey("RegNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MIUPortal.API.Models.Notification", b =>
                {
                    b.HasOne("MIUPortal.API.Models.Student", "Student")
                        .WithMany("Notifications")
                        .HasForeignKey("RegNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MIUPortal.API.Models.Payment", b =>
                {
                    b.HasOne("MIUPortal.API.Models.Student", "Student")
                        .WithMany("Payments")
                        .HasForeignKey("RegNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MIUPortal.API.Models.Result", b =>
                {
                    b.HasOne("MIUPortal.API.Models.Student", "Student")
                        .WithMany("Results")
                        .HasForeignKey("RegNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MIUPortal.API.Models.SemesterRegistration", b =>
                {
                    b.HasOne("MIUPortal.API.Models.Student", "Student")
                        .WithMany("SemesterRegistrations")
                        .HasForeignKey("RegNumber")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Student");
                });

            modelBuilder.Entity("MIUPortal.API.Models.Course", b =>
                {
                    b.Navigation("CourseEnrollments");
                });

            modelBuilder.Entity("MIUPortal.API.Models.Student", b =>
                {
                    b.Navigation("CourseEnrollments");

                    b.Navigation("Documents");

                    b.Navigation("FinancialTransactions");

                    b.Navigation("Notifications");

                    b.Navigation("Payments");

                    b.Navigation("Results");

                    b.Navigation("SemesterRegistrations");
                });
#pragma warning restore 612, 618
        }
    }
}
